Repository blockchain/My-Wallet-V3-iOS, pull requests merged in 2018-09, with the labels that each got.

#456 fix(HB): Fixes some bugs in handling pagination on the exchange list screen.
  Blockchain/Homebrew/Exchange/DataProviders/ExchangeListDataProvider.swift
  Blockchain/Homebrew/Exchange/Interactors/ExchangeListInteractor.swift
  Blockchain/Homebrew/Exchange/Services/ExchangeService.swift
  Blockchain/Homebrew/Exchange/Views/Cells/LoadingTableViewCell.swift
  Blockchain/Homebrew/Exchange/Views/Cells/LoadingTableViewCell.xib
  Blockchain/Homebrew/Exchange/Views/ExchangeListHeaderView.xib
Labels: Ready for Review

#449 feat(HB): Adding TradingPairView
  Blockchain.xcodeproj/project.pbxproj
  Blockchain/AssetType.swift
  Blockchain/Homebrew/Exchange/Views/TradingPairView.swift
  Blockchain/Homebrew/Exchange/Views/TradingPairView.xib
  Blockchain/Models/ViewModels/PresentationUpdate/AnimatablePresentationUpdate.swift
  Blockchain/Models/ViewModels/PresentationUpdate/ListPresentationUpdate.swift
  Blockchain/Models/ViewModels/PresentationUpdate/TransitionPresentationUpdate.swift
  Blockchain/Resources/Images.xcassets/Icon-BCH.imageset/Contents.json
  Blockchain/Resources/Images.xcassets/Icon-BCH.imageset/Icon-BCH.pdf
  Blockchain/Resources/Images.xcassets/Icon-BTC.imageset/Contents.json
  Blockchain/Resources/Images.xcassets/Icon-BTC.imageset/Icon-BTC.pdf
  Blockchain/Resources/Images.xcassets/Icon-ETH.imageset/Contents.json
  Blockchain/Resources/Images.xcassets/Icon-ETH.imageset/Icon-ETH.pdf
  Blockchain/Resources/Images.xcassets/Icon-Exchange.imageset/Contents.json
  Blockchain/Resources/Images.xcassets/Icon-Exchange.imageset/Icon-Exchange.pdf
Labels: Ready for Review

#444 feat(HB): IOS-1231 - Models and REST endpoints for exchange
  Blockchain.xcodeproj/project.pbxproj
  Blockchain/Coordinators/BuySellCoordinator.swift
  Blockchain/Coordinators/ExchangeCoordinator.swift
  Blockchain/Homebrew/Exchange/API/RatesAPI.swift
  Blockchain/Homebrew/Exchange/API/TradeExecutionAPI.swift
  Blockchain/Homebrew/Exchange/Models/Limit.swift
  Blockchain/Homebrew/Exchange/Models/Order.swift
  Blockchain/Homebrew/Exchange/Models/Rates.swift
  Blockchain/Homebrew/Exchange/Models/TradeLimits.swift
  Blockchain/Homebrew/Exchange/Models/TradingPair.swift
  Blockchain/Homebrew/Exchange/Models/TradingPairConfiguration.swift
  Blockchain/Homebrew/Exchange/Services/RatesService.swift
  Blockchain/Homebrew/Exchange/Services/TradeExecutionService.swift
  Blockchain/Models/Trade.swift
  Blockchain/Network/NetworkRequest.swift
  Blockchain/Wallet/WalletBuySellDelegate.swift
  Blockchain/Wallet/WalletManager.swift
Labels: Ready for Review

#464 feat(KYC): IOS-1142 restore view state if user drops of mid-flow.
  Blockchain/Homebrew/Exchange/Services/MarketsService.swift
  Blockchain/KYC/Address/KYCAddressController.swift
  Blockchain/KYC/KYCCoordinator.swift
  Blockchain/KYC/KYCPageViewFactory.swift
  Blockchain/KYC/Mobile Number/KYCConfirmPhoneNumberController.swift
  Blockchain/KYC/Mobile Number/KYCEnterPhoneNumberController.swift
  Blockchain/KYC/Models/KYCPageModel.swift
  Blockchain/KYC/Personal/KYCPersonalDetailsController.swift
  Blockchain/LocalizationConstants.swift
  Blockchain/Views/ValidationTextField/ValidationDateField/ValidationDateField.swift
Labels: Ready for Review

#466 feat(KYC): add UNDER_REVIEW account state (IOS-1234)
  Blockchain/KYC/Information/KYCInformationViewModel.swift
  Blockchain/KYC/KYCCoordinator.swift
  Blockchain/KYC/Models/KYCAccountStatus.swift
  Blockchain/Settings/Settings+Helpers.swift
Labels: don't merge yet, feedback-needed

#465 feat(Homebrew): Exchange Detail Screens and related UI components
  Blockchain.xcodeproj/project.pbxproj
  Blockchain/Homebrew/Exchange/Controllers/ExchangeDetailViewController/ExchangeDetailCoordinator.swift
  Blockchain/Homebrew/Exchange/Controllers/ExchangeDetailViewController/ExchangeDetailInterface.swift
  Blockchain/Homebrew/Exchange/Controllers/ExchangeDetailViewController/ExchangeDetailViewController.storyboard
  Blockchain/Homebrew/Exchange/Controllers/ExchangeDetailViewController/ExchangeDetailViewController.swift
  Blockchain/Homebrew/Exchange/Models/CellModels/ExchangeCellModel.swift
  Blockchain/Homebrew/Exchange/Models/CellModels/ExchangeTradeCellModel.swift
  Blockchain/Homebrew/Exchange/Views/Cells/DetailCollectionViewCells/Base/ExchangeDetailCell.swift
  Blockchain/Homebrew/Exchange/Views/Cells/DetailCollectionViewCells/Plain/PlainCell.swift
  Blockchain/Homebrew/Exchange/Views/Cells/DetailCollectionViewCells/Plain/PlainCell.xib
  Blockchain/Homebrew/Exchange/Views/Cells/DetailCollectionViewCells/Text/TextCell.swift
  Blockchain/Homebrew/Exchange/Views/Cells/DetailCollectionViewCells/Text/TextCell.xib
  Blockchain/Homebrew/Exchange/Views/Cells/DetailCollectionViewCells/TradingPair/TradingPairCell.swift
  Blockchain/Homebrew/Exchange/Views/Cells/DetailCollectionViewCells/TradingPair/TradingPairCell.xib
  Blockchain/Homebrew/Exchange/Views/Footers/ActionableFooterView.swift
  Blockchain/Homebrew/Exchange/Views/Footers/ActionableFooterView.xib
  Blockchain/Homebrew/Exchange/Views/Headers/ExchangeDetailHeaderView.swift
  Blockchain/Homebrew/Exchange/Views/Headers/ExchangeDetailHeaderView.xib
  Blockchain/Homebrew/Exchange/Views/Headers/ExchangeLockedHeaderView.swift
  Blockchain/Homebrew/Exchange/Views/Headers/ExchangeLockedHeaderView.xib
  Blockchain/Homebrew/Exchange/Views/Headers/SectionHeaders/ExchangeListHeaderView.swift
  Blockchain/Homebrew/Exchange/Views/Headers/SectionHeaders/ExchangeListHeaderView.xib
  Blockchain/Homebrew/Exchange/Views/TradingPairView.swift
  Blockchain/Homebrew/Exchange/Views/TradingPairView.xib
  Blockchain/LocalizationConstants.swift
  Blockchain/Models/Trade.swift
  Blockchain/Models/ViewModels/LayoutAttributes.swift
  Blockchain/Resources/Images.xcassets/Icon-Lock.imageset/Contents.json
  Blockchain/Resources/Images.xcassets/Icon-Lock.imageset/Lock (1).pdf
  Blockchain/Resources/Images.xcassets/Icon-SingleArrow.imageset/Contents.json
  Blockchain/Resources/Images.xcassets/Icon-SingleArrow.imageset/Icon-SingleArrow.pdf
Labels: Ready for Review

#477 feat(HB): WIP for ExchangeCreateViewController design
  Blockchain.xcodeproj/project.pbxproj
  Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.storyboard
  Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.swift
  Blockchain/Homebrew/Exchange/Controllers/ExchangeDetailViewController/ExchangeDetailCoordinator.swift
  Blockchain/Homebrew/Exchange/Controllers/ExchangeDetailViewController/ExchangeDetailInterface.swift
  Blockchain/Homebrew/Exchange/Controllers/ExchangeDetailViewController/ExchangeDetailViewController.storyboard
  Blockchain/Homebrew/Exchange/Controllers/ExchangeDetailViewController/ExchangeDetailViewController.swift
  Blockchain/Homebrew/Exchange/Models/CellModels/ExchangeCellModel.swift
  Blockchain/Homebrew/Exchange/Models/CellModels/ExchangeTradeCellModel.swift
  Blockchain/Homebrew/Exchange/Views/Cells/DetailCollectionViewCells/Base/ExchangeDetailCell.swift
  Blockchain/Homebrew/Exchange/Views/Cells/DetailCollectionViewCells/Plain/PlainCell.swift
  Blockchain/Homebrew/Exchange/Views/Cells/DetailCollectionViewCells/Plain/PlainCell.xib
  Blockchain/Homebrew/Exchange/Views/Cells/DetailCollectionViewCells/Text/TextCell.swift
  Blockchain/Homebrew/Exchange/Views/Cells/DetailCollectionViewCells/Text/TextCell.xib
  Blockchain/Homebrew/Exchange/Views/Cells/DetailCollectionViewCells/TradingPair/TradingPairCell.swift
  Blockchain/Homebrew/Exchange/Views/Cells/DetailCollectionViewCells/TradingPair/TradingPairCell.xib
  Blockchain/Homebrew/Exchange/Views/Footers/ActionableFooterView.swift
  Blockchain/Homebrew/Exchange/Views/Footers/ActionableFooterView.xib
  Blockchain/Homebrew/Exchange/Views/Headers/ExchangeDetailHeaderView.swift
  Blockchain/Homebrew/Exchange/Views/Headers/ExchangeDetailHeaderView.xib
  Blockchain/Homebrew/Exchange/Views/Headers/ExchangeLockedHeaderView.swift
  Blockchain/Homebrew/Exchange/Views/Headers/ExchangeLockedHeaderView.xib
  Blockchain/Homebrew/Exchange/Views/Headers/SectionHeaders/ExchangeListHeaderView.swift
  Blockchain/Homebrew/Exchange/Views/Headers/SectionHeaders/ExchangeListHeaderView.xib
  Blockchain/Homebrew/Exchange/Views/TradingPairView.swift
  Blockchain/Homebrew/Exchange/Views/TradingPairView.xib
  Blockchain/Homebrew/Models/NabuUser.swift
  Blockchain/KYC/Address/KYCAddressController.swift
  Blockchain/KYC/Search/Models/PostalAddress.swift
  Blockchain/LocalizationConstants.swift
  Blockchain/Models/Trade.swift
  Blockchain/Models/ViewModels/LayoutAttributes.swift
  Blockchain/Resources/Images.xcassets/Bolete.imageset/Bolete.pdf
  Blockchain/Resources/Images.xcassets/Bolete.imageset/Contents.json
  Blockchain/Resources/Images.xcassets/Icon-Lock.imageset/Contents.json
  Blockchain/Resources/Images.xcassets/Icon-Lock.imageset/Lock (1).pdf
  Blockchain/Resources/Images.xcassets/Icon-SingleArrow.imageset/Contents.json
  Blockchain/Resources/Images.xcassets/Icon-SingleArrow.imageset/Icon-SingleArrow.pdf
  Blockchain/Resources/Images.xcassets/Icon-Switch.imageset/Contents.json
  Blockchain/Resources/Images.xcassets/Icon-Switch.imageset/Icon-Switch.pdf
  Blockchain/Resources/Images.xcassets/TapArrows.imageset/Contents.json
  Blockchain/Resources/Images.xcassets/TapArrows.imageset/TapArrows.pdf
  Blockchain/View Controllers/BCNavigationController.h
  Blockchain/View Controllers/BCNavigationController.m
  Blockchain/Views/Keypad/NumberKeypadView.swift
  Blockchain/Views/Keypad/NumberKeypadView.xib
  Blockchain/Views/NibBasedView.swift
Labels: Ready for Review

#475 fix(KYC): IOS-1245 IOS-1217 IOS-1179 Personal details UI polish.
  Blockchain.xcodeproj/project.pbxproj
  Blockchain/Arrays.swift
  Blockchain/Extensions/Collection+Helpers.swift
  Blockchain/KYC/Personal/KYCPersonalDetailsController.swift
  Blockchain/KYC/Storyboards/Base.lproj/KYCPersonalDetailsController.storyboard
  Blockchain/Views/ValidationForm/ValidationFormView.swift
  BlockchainTests/Extensions/Collection+HelpersTests.swift
Labels: Ready for Review

#496 feat(HB): Number Entry UX Behavior IOS-1284
  Blockchain.xcodeproj/project.pbxproj
  Blockchain/Extensions/NSAttributedString+Conveniences.swift
  Blockchain/Extensions/UIView.swift
  Blockchain/Homebrew/Exchange/API/ExchangeCreateContracts.swift
  Blockchain/Homebrew/Exchange/API/ExchangeInputsAPI.swift
  Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.storyboard
  Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.swift
  Blockchain/Homebrew/Exchange/DataProviders/ExchangeInputComponent.swift
  Blockchain/Homebrew/Exchange/DataProviders/ExchangeInputs.swift
  Blockchain/Homebrew/Exchange/Interactors/ExchangeCreateInteractor.swift
  Blockchain/Homebrew/Exchange/Models/ExchangeStyleTemplate.swift
  Blockchain/Homebrew/Exchange/Models/InputComponent.swift
  Blockchain/Homebrew/Exchange/Models/NumberInputViewModel.swift
  Blockchain/Homebrew/Exchange/Presenters/ExchangeCreatePresenter.swift
  Blockchain/Homebrew/Exchange/Services/ExchangeConversionService.swift
  Blockchain/Homebrew/Exchange/Services/ExchangeInputsService.swift
  Blockchain/Views/Keypad/NumberKeypadView.swift
  Blockchain/Views/Keypad/NumberKeypadView.xib
  BlockchainTests/Homebrew/NumberInputTests.swift
Labels: Ready for Review

#505 feat(Exchange): IOS-1195 swap fix.
  Blockchain/Homebrew/Exchange/API/ExchangeInputsAPI.swift
  Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.swift
  Blockchain/Homebrew/Exchange/DataProviders/ExchangeInputComponent.swift
  Blockchain/Homebrew/Exchange/Interactors/ExchangeCreateInteractor.swift
  Blockchain/Homebrew/Exchange/Models/Fix.swift
  Blockchain/Homebrew/Exchange/Models/InputComponent.swift
  Blockchain/Homebrew/Exchange/Models/MarketsModel.swift
  Blockchain/Homebrew/Exchange/Presenters/ExchangeCreatePresenter.swift
  Blockchain/Homebrew/Exchange/Services/ExchangeConversionService.swift
  Blockchain/Homebrew/Exchange/Services/ExchangeInputsService.swift
Labels: Ready for Review

#509 feat(HB): Conversion Rates View - IOS-1208
  Blockchain.xcodeproj/project.pbxproj
  Blockchain/Arrays.swift
  Blockchain/Homebrew/Exchange/API/ExchangeCreateContracts.swift
  Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.storyboard
  Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.swift
  Blockchain/Homebrew/Exchange/Interactors/ExchangeCreateInteractor.swift
  Blockchain/Homebrew/Exchange/Presenters/ExchangeCreatePresenter.swift
  Blockchain/Homebrew/Exchange/Views/ConversionRatesView.swift
  Blockchain/Homebrew/Exchange/Views/ConversionRatesView.xib
  Blockchain/Models/SocketMessage.swift
  Blockchain/Resources/Images.xcassets/up_chevron.imageset/Contents.json
  Blockchain/Resources/Images.xcassets/up_chevron.imageset/up_chevron.pdf
  Blockchain/Views/Keypad/NumberKeypadView.swift
Labels: Ready for Review

#513 feat(HB): Fetching Homebrew trades with new HB model type.
  Blockchain/Coordinators/ExchangeCoordinator.swift
  Blockchain/Homebrew/Exchange/API/ExchangeListContracts.swift
  Blockchain/Homebrew/Exchange/API/PartnerExchangeAPI.swift
  Blockchain/Homebrew/Exchange/Controllers/ExchangeDetailViewController.swift
  Blockchain/Homebrew/Exchange/Controllers/ExchangeListViewController.swift
  Blockchain/Homebrew/Exchange/DataProviders/ExchangeListDataProvider.swift
  Blockchain/Homebrew/Exchange/Interactors/ExchangeListInteractor.swift
  Blockchain/Homebrew/Exchange/Models/CellModels/ExchangeTradeCellModel.swift
  Blockchain/Homebrew/Exchange/Presenters/ExchangeListPresenter.swift
  Blockchain/Homebrew/Exchange/Services/ExchangeService.swift
  Blockchain/Homebrew/Exchange/Services/HomebrewExchangeService.swift
  Blockchain/Homebrew/Exchange/Services/PartnerExchangeService.swift
  Blockchain/Homebrew/Exchange/Views/Cells/ExchangeListViewCell.swift
  Blockchain/LocalizationConstants.swift
Labels: Ready for Review

#515 fix(Exchange): unsubscribe from unused currency pair.
  Blockchain/Homebrew/Exchange/Interactors/ExchangeCreateInteractor.swift
  Blockchain/Homebrew/Exchange/Services/MarketsService.swift
  Blockchain/Network/Models/SocketMessage.swift
  Blockchain/Network/SocketManager.swift
Labels: plan changes

#517 feat(Exchange): IOS-1322 Checking balances when computing min/max
  Blockchain/Accounts/AssetAccount.swift
  Blockchain/Accounts/AssetAccountRepository.swift
  Blockchain/AssetType.swift
  Blockchain/Homebrew/Exchange/API/ExchangeCreateContracts.swift
  Blockchain/Homebrew/Exchange/API/TradeLimitsAPI.swift
  Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.swift
  Blockchain/Homebrew/Exchange/Interactors/ExchangeCreateInteractor.swift
  Blockchain/Homebrew/Exchange/Presenters/ExchangeCreatePresenter.swift
  Blockchain/Homebrew/Exchange/Services/MarketsService.swift
  Blockchain/Homebrew/Exchange/Services/TradeLimitsService.swift
  Blockchain/Network/Models/SocketMessage.swift
  Blockchain/Network/SocketManager.swift
Labels: Ready for Review

#523 feat(HB): IOS-1312 - All currencies should show when selecting source
  Blockchain/Accounts/AssetAccount.swift
  Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.swift
Labels: Ready for Review

#526 fix(HB): Fixes issue where tapping New Exchange showed exchange details.
  Blockchain/Homebrew/Exchange/DataProviders/ExchangeListDataProvider.swift
  Blockchain/Homebrew/Exchange/Views/Cells/NewOrderTableViewCell.xib
Labels: Ready for Review

#528 feat(HB): Adding `BounceButton`
  Blockchain.xcodeproj/project.pbxproj
  Blockchain/Views/Buttons/BounceButton.swift
  Blockchain/Views/Keypad/NumberKeypadView.xib
Labels: Ready for Review

#534 fix(HB): IOS-1312 - All accounts should show in the alert controller
  Blockchain/Homebrew/Exchange/API/ExchangeCreateContracts.swift
  Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.swift
  Blockchain/Homebrew/Exchange/Interactors/ExchangeCreateInteractor.swift
  Blockchain/Homebrew/Exchange/Models/MarketsModel.swift
  Blockchain/Homebrew/Exchange/Presenters/ExchangeAssetAccountListPresenter.swift
  Blockchain/Homebrew/Exchange/Presenters/ExchangeCreatePresenter.swift
Labels: Ready for Review

#542 fix(Send): IOS-1314 - Fixing unrecognized selector crash
  Blockchain/View Controllers/SendEtherViewController.m
Labels: Ready for Review

#531 fix(Order history): IOS-1339 - Not showing pending trade
  Blockchain/Constants.swift
  Blockchain/Extensions/DateFormatter+Conveniences.swift
  Blockchain/Homebrew/Exchange/Controllers/ExchangeListViewController.swift
  Blockchain/Homebrew/Exchange/ExchangeDetailCoordinator.swift
  Blockchain/Homebrew/Exchange/Interactors/ExchangeListInteractor.swift
  Blockchain/Homebrew/Exchange/Models/CellModels/ExchangeCellModel.swift
  Blockchain/Homebrew/Exchange/Models/CellModels/ExchangeTradeCellModel.swift
  Blockchain/Homebrew/Exchange/Services/ExchangeService.swift
  Blockchain/Homebrew/Exchange/Services/HomebrewExchangeService.swift
  Blockchain/Homebrew/Exchange/Views/Cells/DetailCollectionViewCells/Plain/PlainCell.swift
Labels: Ready for Review

#540 fix(HB): Fixing issue where multiple trades could be submitted.
  Blockchain/Homebrew/Exchange/API/ExchangeCreateContracts.swift
  Blockchain/Homebrew/Exchange/API/TradeExecutionAPI.swift
  Blockchain/Homebrew/Exchange/ExchangeDetailCoordinator.swift
  Blockchain/Homebrew/Exchange/Interactors/ExchangeCreateInteractor.swift
  Blockchain/Homebrew/Exchange/Presenters/ExchangeCreatePresenter.swift
  Blockchain/Homebrew/Exchange/Services/TradeExecutionService.swift
  Blockchain/Models/Wallet.h
  Blockchain/Models/Wallet.m
Labels: Ready for Review

#544 fix(KYC): IOS-1310 - Autocomplete leaves address field blank
  Blockchain/KYC/Address/KYCAddressController.swift
Labels: Ready for Review

#538 fix(HB): IOS-1319 - Adding `SocketError` and error subscribing to `ExchangeInteractor`
  Blockchain/Homebrew/Exchange/Interactors/ExchangeCreateInteractor.swift
  Blockchain/Homebrew/Exchange/Services/MarketsService.swift
  Blockchain/Network/Models/SocketMessage.swift
  Blockchain/Network/SocketManager.swift
Labels: Ready for Review

#546 fix(HB): IOS-1368 - `Withdrawal` SymbolValue can sometimes be nil resulting in no trade history
  Blockchain/Homebrew/Exchange/Controllers/ExchangeListViewController.swift
  Blockchain/Homebrew/Exchange/Models/CellModels/ExchangeTradeCellModel.swift
  Blockchain/Homebrew/Exchange/Views/Cells/ExchangeListViewCell.swift
Labels: Ready for Review

#547 fix(Websocket): close exchange WS when no longer needed.
  Blockchain.xcodeproj/project.pbxproj
  Blockchain/Homebrew/Exchange/Services/MarketsService.swift
  Blockchain/Network/SocketManager.swift
  BlockchainTests/Homebrew/Exchange/Services/MarketsServiceTests.swift
  BlockchainTests/Mock/MockSocketManager.swift
Labels: Ready for Review

#552 fix(OrderHistory) - IOS-1343 - Order history fields for partner trades were blank and/or incorrect
  Blockchain/Accounts/AssetAccountRepository.swift
  Blockchain/Homebrew/Exchange/Controllers/ExchangeDetailViewController.swift
  Blockchain/Homebrew/Exchange/ExchangeDetailCoordinator.swift
  Blockchain/Homebrew/Exchange/Models/CellModels/ExchangeTradeCellModel.swift
  Blockchain/Homebrew/Exchange/Views/Cells/ExchangeListViewCell.swift
  Blockchain/Models/ExchangeTrade.h
  Blockchain/Models/ExchangeTrade.m
Labels: Ready for Review
