Repository blockchain/My-Wallet-V3-iOS, pull requests merged in 2018-03, with the labels that each got.

#64 Bch addresses
  Blockchain/AccountTableCell.h
  Blockchain/AccountTableCell.m
  Blockchain/AccountsAndAddressesDetailViewController.h
  Blockchain/AccountsAndAddressesDetailViewController.m
  Blockchain/AccountsAndAddressesNavigationController.m
  Blockchain/AccountsAndAddressesViewController.h
  Blockchain/AccountsAndAddressesViewController.m
  Blockchain/AssetSelectorView.h
  Blockchain/AssetSelectorView.m
  Blockchain/BCAddressSelectionView.m
  Blockchain/BCContactRequestView.m
  Blockchain/BCEditAccountView.h
  Blockchain/BCEditAccountView.m
  Blockchain/ExchangeCreateViewController.m
  Blockchain/PrivateKeyReader.h
  Blockchain/PrivateKeyReader.m
  Blockchain/ReceiveCoinsViewController.m
  Blockchain/RootService.m
  Blockchain/SendBitcoinViewController.m
  Blockchain/SendEtherViewController.m
  Blockchain/SideMenuViewController.m
  Blockchain/TabViewController.m
  Blockchain/TransactionsBitcoinViewController.m
  Blockchain/TransferAllFundsBuilder.h
  Blockchain/TransferAllFundsBuilder.m
  Blockchain/TransferAllFundsViewController.m
  Blockchain/Wallet.h
  Blockchain/Wallet.m
  Blockchain/js/wallet-ios.js
Labels: WIP

#72 SwiftLint
  .swiftlint.yml
  Blockchain.xcodeproj/project.pbxproj
Labels: WIP, don't merge yet

#75 feat(Images): add BCH images
  Artwork/Gruntfile.coffee
  Artwork/bitcoin_cash_white.svg
  Artwork/chevron_down_white.svg
  Artwork/chevron_right_white.svg
  Artwork/ether.svg
  Blockchain/AssetSelectionTableViewCell.m
  Blockchain/BCPricePreviewView.h
  Blockchain/BCPricePreviewView.m
  Blockchain/DashboardViewController.m
  Blockchain/TransactionsViewController.m
  Images.xcassets/bitcoin_cash_white.imageset/Contents.json
  Images.xcassets/chevron_down_white.imageset/Contents.json
  Images.xcassets/chevron_right_white.imageset/Contents.json
  Images.xcassets/ether.imageset/Contents.json
Labels: don't merge yet

#77 BCH UI Updates
  Blockchain/BCBalancesChartView.m
  Blockchain/BackupVerifyViewController.swift
  Blockchain/BackupWordsViewController.swift
  Blockchain/Blockchain-Prefix.pch
  Blockchain/DashboardViewController.m
  Blockchain/LocalizationConstants.h
  Blockchain/ReceiveBitcoinViewController.m
Labels: WIP, don't merge yet
